# Generated by Django 4.2 on 2023-04-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointypes',
            name='minimum_purchase',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cointypes',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
