# Generated by Django 4.2 on 2023-04-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_remove_cointypes_minimum_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointypes',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
